package com.bochat.app.model.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.bochat.app.model.bean.SpeedConverStatusEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "table_speed_conver".
*/
public class SpeedConverStatusEntityDao extends AbstractDao<SpeedConverStatusEntity, Long> {

    public static final String TABLENAME = "table_speed_conver";

    /**
     * Properties of entity SpeedConverStatusEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, long.class, "id", true, "_id");
        public final static Property Status = new Property(1, int.class, "status", false, "STATUS");
        public final static Property Des = new Property(2, String.class, "des", false, "DES");
    };


    public SpeedConverStatusEntityDao(DaoConfig config) {
        super(config);
    }
    
    public SpeedConverStatusEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"table_speed_conver\" (" + //
                "\"_id\" INTEGER PRIMARY KEY NOT NULL ," + // 0: id
                "\"STATUS\" INTEGER NOT NULL ," + // 1: status
                "\"DES\" TEXT);"); // 2: des
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"table_speed_conver\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, SpeedConverStatusEntity entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
        stmt.bindLong(2, entity.getStatus());
 
        String des = entity.getDes();
        if (des != null) {
            stmt.bindString(3, des);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, SpeedConverStatusEntity entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
        stmt.bindLong(2, entity.getStatus());
 
        String des = entity.getDes();
        if (des != null) {
            stmt.bindString(3, des);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public SpeedConverStatusEntity readEntity(Cursor cursor, int offset) {
        SpeedConverStatusEntity entity = new SpeedConverStatusEntity( //
            cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // status
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // des
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, SpeedConverStatusEntity entity, int offset) {
        entity.setId(cursor.getLong(offset + 0));
        entity.setStatus(cursor.getInt(offset + 1));
        entity.setDes(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(SpeedConverStatusEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(SpeedConverStatusEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
