package com.bochat.app.model.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.bochat.app.model.bean.FriendEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "table_friends".
*/
public class FriendEntityDao extends AbstractDao<FriendEntity, Long> {

    public static final String TABLENAME = "table_friends";

    /**
     * Properties of entity FriendEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, long.class, "id", true, "_id");
        public final static Property Account = new Property(1, String.class, "account", false, "ACCOUNT");
        public final static Property Nickname = new Property(2, String.class, "nickname", false, "NICKNAME");
        public final static Property IsInit = new Property(3, int.class, "isInit", false, "IS_INIT");
        public final static Property Head_img = new Property(4, String.class, "head_img", false, "HEAD_IMG");
        public final static Property Signature = new Property(5, String.class, "signature", false, "SIGNATURE");
        public final static Property Sex = new Property(6, int.class, "sex", false, "SEX");
        public final static Property Age = new Property(7, int.class, "age", false, "AGE");
        public final static Property Province = new Property(8, String.class, "province", false, "PROVINCE");
        public final static Property City = new Property(9, String.class, "city", false, "CITY");
        public final static Property Token = new Property(10, String.class, "token", false, "TOKEN");
        public final static Property Other_id = new Property(11, String.class, "other_id", false, "OTHER_ID");
        public final static Property InviteCode = new Property(12, String.class, "inviteCode", false, "INVITE_CODE");
        public final static Property Countries = new Property(13, String.class, "countries", false, "COUNTRIES");
        public final static Property Birthday = new Property(14, String.class, "birthday", false, "BIRTHDAY");
        public final static Property Area = new Property(15, String.class, "area", false, "AREA");
        public final static Property Relation_state = new Property(16, String.class, "relation_state", false, "RELATION_STATE");
        public final static Property Black_state = new Property(17, String.class, "black_state", false, "BLACK_STATE");
        public final static Property FirstPinYin = new Property(18, String.class, "firstPinYin", false, "FIRST_PIN_YIN");
        public final static Property Type = new Property(19, int.class, "type", false, "TYPE");
        public final static Property Note = new Property(20, String.class, "note", false, "NOTE");
        public final static Property Address = new Property(21, String.class, "address", false, "ADDRESS");
        public final static Property Friend_state = new Property(22, int.class, "friend_state", false, "FRIEND_STATE");
    };


    public FriendEntityDao(DaoConfig config) {
        super(config);
    }
    
    public FriendEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"table_friends\" (" + //
                "\"_id\" INTEGER PRIMARY KEY NOT NULL ," + // 0: id
                "\"ACCOUNT\" TEXT," + // 1: account
                "\"NICKNAME\" TEXT," + // 2: nickname
                "\"IS_INIT\" INTEGER NOT NULL ," + // 3: isInit
                "\"HEAD_IMG\" TEXT," + // 4: head_img
                "\"SIGNATURE\" TEXT," + // 5: signature
                "\"SEX\" INTEGER NOT NULL ," + // 6: sex
                "\"AGE\" INTEGER NOT NULL ," + // 7: age
                "\"PROVINCE\" TEXT," + // 8: province
                "\"CITY\" TEXT," + // 9: city
                "\"TOKEN\" TEXT," + // 10: token
                "\"OTHER_ID\" TEXT," + // 11: other_id
                "\"INVITE_CODE\" TEXT," + // 12: inviteCode
                "\"COUNTRIES\" TEXT," + // 13: countries
                "\"BIRTHDAY\" TEXT," + // 14: birthday
                "\"AREA\" TEXT," + // 15: area
                "\"RELATION_STATE\" TEXT," + // 16: relation_state
                "\"BLACK_STATE\" TEXT," + // 17: black_state
                "\"FIRST_PIN_YIN\" TEXT," + // 18: firstPinYin
                "\"TYPE\" INTEGER NOT NULL ," + // 19: type
                "\"NOTE\" TEXT," + // 20: note
                "\"ADDRESS\" TEXT," + // 21: address
                "\"FRIEND_STATE\" INTEGER NOT NULL );"); // 22: friend_state
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"table_friends\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, FriendEntity entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String account = entity.getAccount();
        if (account != null) {
            stmt.bindString(2, account);
        }
 
        String nickname = entity.getNickname();
        if (nickname != null) {
            stmt.bindString(3, nickname);
        }
        stmt.bindLong(4, entity.getIsInit());
 
        String head_img = entity.getHead_img();
        if (head_img != null) {
            stmt.bindString(5, head_img);
        }
 
        String signature = entity.getSignature();
        if (signature != null) {
            stmt.bindString(6, signature);
        }
        stmt.bindLong(7, entity.getSex());
        stmt.bindLong(8, entity.getAge());
 
        String province = entity.getProvince();
        if (province != null) {
            stmt.bindString(9, province);
        }
 
        String city = entity.getCity();
        if (city != null) {
            stmt.bindString(10, city);
        }
 
        String token = entity.getToken();
        if (token != null) {
            stmt.bindString(11, token);
        }
 
        String other_id = entity.getOther_id();
        if (other_id != null) {
            stmt.bindString(12, other_id);
        }
 
        String inviteCode = entity.getInviteCode();
        if (inviteCode != null) {
            stmt.bindString(13, inviteCode);
        }
 
        String countries = entity.getCountries();
        if (countries != null) {
            stmt.bindString(14, countries);
        }
 
        String birthday = entity.getBirthday();
        if (birthday != null) {
            stmt.bindString(15, birthday);
        }
 
        String area = entity.getArea();
        if (area != null) {
            stmt.bindString(16, area);
        }
 
        String relation_state = entity.getRelation_state();
        if (relation_state != null) {
            stmt.bindString(17, relation_state);
        }
 
        String black_state = entity.getBlack_state();
        if (black_state != null) {
            stmt.bindString(18, black_state);
        }
 
        String firstPinYin = entity.getFirstPinYin();
        if (firstPinYin != null) {
            stmt.bindString(19, firstPinYin);
        }
        stmt.bindLong(20, entity.getType());
 
        String note = entity.getNote();
        if (note != null) {
            stmt.bindString(21, note);
        }
 
        String address = entity.getAddress();
        if (address != null) {
            stmt.bindString(22, address);
        }
        stmt.bindLong(23, entity.getFriend_state());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, FriendEntity entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String account = entity.getAccount();
        if (account != null) {
            stmt.bindString(2, account);
        }
 
        String nickname = entity.getNickname();
        if (nickname != null) {
            stmt.bindString(3, nickname);
        }
        stmt.bindLong(4, entity.getIsInit());
 
        String head_img = entity.getHead_img();
        if (head_img != null) {
            stmt.bindString(5, head_img);
        }
 
        String signature = entity.getSignature();
        if (signature != null) {
            stmt.bindString(6, signature);
        }
        stmt.bindLong(7, entity.getSex());
        stmt.bindLong(8, entity.getAge());
 
        String province = entity.getProvince();
        if (province != null) {
            stmt.bindString(9, province);
        }
 
        String city = entity.getCity();
        if (city != null) {
            stmt.bindString(10, city);
        }
 
        String token = entity.getToken();
        if (token != null) {
            stmt.bindString(11, token);
        }
 
        String other_id = entity.getOther_id();
        if (other_id != null) {
            stmt.bindString(12, other_id);
        }
 
        String inviteCode = entity.getInviteCode();
        if (inviteCode != null) {
            stmt.bindString(13, inviteCode);
        }
 
        String countries = entity.getCountries();
        if (countries != null) {
            stmt.bindString(14, countries);
        }
 
        String birthday = entity.getBirthday();
        if (birthday != null) {
            stmt.bindString(15, birthday);
        }
 
        String area = entity.getArea();
        if (area != null) {
            stmt.bindString(16, area);
        }
 
        String relation_state = entity.getRelation_state();
        if (relation_state != null) {
            stmt.bindString(17, relation_state);
        }
 
        String black_state = entity.getBlack_state();
        if (black_state != null) {
            stmt.bindString(18, black_state);
        }
 
        String firstPinYin = entity.getFirstPinYin();
        if (firstPinYin != null) {
            stmt.bindString(19, firstPinYin);
        }
        stmt.bindLong(20, entity.getType());
 
        String note = entity.getNote();
        if (note != null) {
            stmt.bindString(21, note);
        }
 
        String address = entity.getAddress();
        if (address != null) {
            stmt.bindString(22, address);
        }
        stmt.bindLong(23, entity.getFriend_state());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public FriendEntity readEntity(Cursor cursor, int offset) {
        FriendEntity entity = new FriendEntity( //
            cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // account
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // nickname
            cursor.getInt(offset + 3), // isInit
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // head_img
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // signature
            cursor.getInt(offset + 6), // sex
            cursor.getInt(offset + 7), // age
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // province
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // city
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // token
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // other_id
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // inviteCode
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // countries
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // birthday
            cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15), // area
            cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16), // relation_state
            cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17), // black_state
            cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18), // firstPinYin
            cursor.getInt(offset + 19), // type
            cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20), // note
            cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21), // address
            cursor.getInt(offset + 22) // friend_state
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, FriendEntity entity, int offset) {
        entity.setId(cursor.getLong(offset + 0));
        entity.setAccount(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setNickname(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setIsInit(cursor.getInt(offset + 3));
        entity.setHead_img(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setSignature(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setSex(cursor.getInt(offset + 6));
        entity.setAge(cursor.getInt(offset + 7));
        entity.setProvince(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setCity(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setToken(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setOther_id(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setInviteCode(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setCountries(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setBirthday(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setArea(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
        entity.setRelation_state(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
        entity.setBlack_state(cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17));
        entity.setFirstPinYin(cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18));
        entity.setType(cursor.getInt(offset + 19));
        entity.setNote(cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20));
        entity.setAddress(cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21));
        entity.setFriend_state(cursor.getInt(offset + 22));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(FriendEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(FriendEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
