package com.bochat.app.model.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.bochat.app.model.bean.TeamEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "table_teams".
*/
public class TeamEntityDao extends AbstractDao<TeamEntity, Long> {

    public static final String TABLENAME = "table_teams";

    /**
     * Properties of entity TeamEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, long.class, "id", true, "_id");
        public final static Property Nickname = new Property(1, String.class, "nickname", false, "NICKNAME");
        public final static Property HeadImg = new Property(2, String.class, "headImg", false, "HEAD_IMG");
    };


    public TeamEntityDao(DaoConfig config) {
        super(config);
    }
    
    public TeamEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"table_teams\" (" + //
                "\"_id\" INTEGER PRIMARY KEY NOT NULL ," + // 0: id
                "\"NICKNAME\" TEXT," + // 1: nickname
                "\"HEAD_IMG\" TEXT);"); // 2: headImg
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"table_teams\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, TeamEntity entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String nickname = entity.getNickname();
        if (nickname != null) {
            stmt.bindString(2, nickname);
        }
 
        String headImg = entity.getHeadImg();
        if (headImg != null) {
            stmt.bindString(3, headImg);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, TeamEntity entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String nickname = entity.getNickname();
        if (nickname != null) {
            stmt.bindString(2, nickname);
        }
 
        String headImg = entity.getHeadImg();
        if (headImg != null) {
            stmt.bindString(3, headImg);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public TeamEntity readEntity(Cursor cursor, int offset) {
        TeamEntity entity = new TeamEntity( //
            cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // nickname
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // headImg
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, TeamEntity entity, int offset) {
        entity.setId(cursor.getLong(offset + 0));
        entity.setNickname(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setHeadImg(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(TeamEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(TeamEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
